# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: $(Build.BuildId)
  
stages:
  - stage: RunTestScript
    jobs:
      - job: RunScript
        steps:
        - bash: echo "Build and Deploy Dotnet App to AKS Cluster"
  - stage: BuildDockerImage
    jobs: 
      - job: BuildImage
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-service-connection'
              repository: 'dotnetapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(tag)'

  - stage: DeployImageToAKS
    jobs:
      - job: DeployImage
        steps:
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'kube-service-connection'
              namespace: 'default'
              manifests: |
                $(System.DefaultWorkingDirectory)/dotnet-terraform-docker-kubernetes-devops/manifests/deployment.yaml
                $(System.DefaultWorkingDirectory)/dotnet-terraform-docker-kubernetes-devops/manifests/service.yaml
              containers: 'vaishuacr0909.azurecr.io/dotnetapp:$(tag)'