# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dotnet-terraform-docker-kubernetes-devops/infrastructure'
    backendAzureRmUseEnvironmentVariablesForAuthentication: false
    backendServiceArm: 'azure-service-connection'
    backendAzureRmResourceGroupName: 'app-grp'
    backendAzureRmStorageAccountName: 'appstorageaccnt0909'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'terraform-dev.tfstate'
    
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dotnet-terraform-docker-kubernetes-devops/infrastructure'
    environmentServiceNameAzureRM: 'azure-service-connection'